// Help center, contextual help, the assistant and the first-run tour, against the real API.
import { expect, test } from './fixtures.js'

test('the first visit walks through the workspace once', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
  const page = await context.newPage()
  await page.goto('/?as=dispatcher')
  const tour = page.getByRole('dialog', { name: 'Tour' })
  await expect(tour).toBeVisible()
  await expect(tour).toContainText('Step 1 of 6')
  await expect(tour.getByRole('heading', { name: 'The recommendation' })).toBeVisible()
  for (let i = 0; i < 5; i++) await tour.getByRole('button', { name: 'Next' }).click()
  await expect(tour.getByRole('heading', { name: 'Help is one key away' })).toBeVisible()
  await tour.getByRole('button', { name: 'Done' }).click()
  await expect(tour).toHaveCount(0)
  await page.reload()
  await expect(page.getByText('5 strategies solved')).toBeAttached()
  await expect(page.getByRole('dialog', { name: 'Tour' })).toHaveCount(0)
  await context.close()
})

test('help opens with ?, searches, and reads an article at the right section', async ({ page, signIn }) => {
  await signIn()
  await page.keyboard.press('?')
  const help = page.getByRole('dialog', { name: 'Help' })
  await expect(help.getByText('Get started').first()).toBeVisible()
  await help.getByRole('searchbox', { name: 'Search help' }).fill('drive the clock')
  await help.getByRole('list', { name: 'Search results' }).getByRole('button').first().click()
  await expect(help.getByRole('heading', { level: 2, name: 'Live dispatch' })).toBeVisible()
  await expect(help.getByRole('heading', { level: 3, name: 'Drive the clock' })).toBeInViewport()
  await page.keyboard.press('Escape')
  await expect(help).toHaveCount(0)
})

test('an ⓘ opens help about that control', async ({ page, signIn }) => {
  await signIn()
  await page.getByRole('button', { name: 'Help: Cost weights' }).click()
  const help = page.getByRole('dialog', { name: 'Help' })
  await expect(help.getByRole('heading', { level: 3, name: 'Soft constraints: the cost weights' })).toBeInViewport()
  await expect(page).toHaveURL(/help=constraints-and-weights/)
})

test('the assistant explains a job from the real plans and opens it', async ({ page, signIn }) => {
  await signIn()
  await page.getByRole('button', { name: 'Ask the assistant' }).click()
  const panel = page.getByRole('dialog', { name: 'Assistant' })
  await panel.getByRole('textbox', { name: 'Your question' }).fill('Why is J006 assigned this way?')
  await panel.getByRole('button', { name: 'Ask', exact: true }).click()
  const log = panel.getByRole('list', { name: 'Conversation' })
  await expect(log.getByText(/\*\*J006\*\*|J006 ·/).first()).toBeVisible()
  await expect(log.getByText('PyVRP:', { exact: false }).first()).toBeVisible()
  await expect(log.getByRole('button', { name: /^Reading the floor plan/ })).toBeVisible()
  await log.getByRole('button', { name: 'Open J006 on the floor plan' }).click()
  await expect(page.getByRole('tab', { name: /Floor plan/ })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('complementary', { name: 'Inspector' }).getByRole('heading', { level: 3 })).toContainText('J006')
})

test('the assistant answers how-to questions with a source, and refuses off-topic ones', async ({ page, signIn }) => {
  await signIn()
  await page.keyboard.press('/')
  const panel = page.getByRole('dialog', { name: 'Assistant' })
  const box = panel.getByRole('textbox', { name: 'Your question' })
  await box.fill('How do I take an engineer off shift?')
  await box.press('Enter')
  await expect(panel.getByRole('button', { name: /^What-if scenarios/ })).toBeVisible()
  await box.fill("What's the weather in Paris?")
  await box.press('Enter')
  await expect(panel.getByText(/^I don't know that one/)).toBeVisible()
  await panel.getByRole('button', { name: /^What-if scenarios/ }).click()
  await expect(page.getByRole('dialog', { name: 'Help' }).getByRole('heading', { level: 2, name: 'What-if scenarios' })).toBeVisible()
})
